### ISSUE TITLE
data issues

### ISSUE THREAD

**Issue by ljc20010323** [wentingwang94/probabilistic-solar-forecasting#1]
Hi, When I review your data, I have two questions.
(1) In the '60947.csv' file, there are two columns, 'SAM_gen' and 'gen_bias'. Which one of them represents the power generation data of the photovoltaic power plant?
(2)When I combine the power data of the Jacumba plant with the ENS data for photovoltaic probability prediction, I'm not sure how to convert the time between the two.
Looking forward to your answer very much!

**Comment by wentingwang94** [comment]
SAM_gen: Modeled generation estimates using NREL’s System Advisory Model (SAM) with project-specific system characteristics reported in EIA Form 860 (augmented by data collected in the context of Berkeley Lab’s Utility-Scale Solar Project) and historical irradiance estimates in NREL’s National Solar Radiation Database (NSRDB).
gen_bias: Modeled generation estimates for a debiasing process that are for the most part identical to SAM_gen. Minor deviations occur for projects where system characteristics were updated after the debiasing process was run, resulting in updated SAM_gen records.

**Comment by ljc20010323** [comment]
Thank you very much!
